language: objective-c
osx_image: xcode10

script:
- xcodebuild -workspace PuzzleMaker.xcworkspace -scheme PuzzleMakerTests -destination "platform=iOS Simulator,name=iPhone XS,OS=12.0" test | xcpretty -c